spring:
  application:
    name: Smart City API
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
#    hikari:
#      maximum-pool-size: 10
#      minimum-idle: 2
#      idle-timeout: 30000
#      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update             # disable auto schema creation
    #show-sql: true                # logs SQL queries in console
    properties:
      hibernate:
        jdbc.time_zone: UTC
        #format_sql: true           # formats SQL for readability
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/master.xml
    enabled: true
logging:
  level:
    root: INFO
    com.mzoubi.smartcity: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"